[package]
name = "notion-async"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
notion = "0.5.1"
tokio = "1.35.1"
clap = { version = "4.4.12", features = ["derive"] }
serde = "1.0.193"
